apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-0507
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      name: dep-0507
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx-con
        image: 734793106345.dkr.ecr.ap-northeast-2.amazonaws.com/web-argo:2
